common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from ellapp.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ellapp/', include('ellapp.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # path for '/'
]

ellapp/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'ellapp'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>', answer_views.answer_vote, name='answer_vote'),
]

ellapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

# Create your models here.

ellapp/forms.py
from django import forms
from ellapp.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question    # model to be used
        fields = ['subject', 'content'] # attributes of the model to be used in QuestionForm
        labels = {
            'subject': 'Subject',
            'content': 'Detail',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': 'Your Answer'
        }

ellapp/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..forms import AnswerForm
from ..models import Question, Answer
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    Ellapp Uploading an Answer
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('ellapp:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'ellapp/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, 'No privilege to modify.')
        return redirect('ellapp:detail', question_id=answer.question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('ellapp:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'ellapp/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, 'No privilege to delete')
    else:
        answer.delete()
    return redirect('ellapp:detail', question_id=answer.question_id)


@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, 'Can\'t recommend yourself')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(
                resolve_url('ellapp:detail', question_id=answer.question.id), answer.id))

ellapp/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q
from ..models import Question

# Create your views here.


def index(request):
    page = request.GET.get('page', '1')     # set page default as 1
    kw = request.GET.get('kw', '')
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(answer__content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()
    paginator = Paginator(question_list, 10)    # show 10 items per page
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'ellapp/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'ellapp/question_detail.html', context)

ellapp/views/question_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from ..forms import QuestionForm
from ..models import Question
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('ellapp:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'ellapp/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, 'No privilege to modify')
        return redirect('ellapp:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.save()
            return redirect('ellapp:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'ellapp/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, 'No privilege to delete!')
        return redirect('ellapp:detail', question_id=question.id)
    question.delete()
    return redirect('ellapp:index')


@login_required(login_url='common:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, 'Cannot recommend yourself')
    else:
        question.voter.add(request.user)
    return redirect('ellapp:detail', question_id=question.id)

templates/ellapp/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- Modify the answer -->
<div class="container my-2">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-2">
            <label for="content" class="form-label">Your Answer</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/ellapp/question_detail.html
{% extends 'base.html' %}
{% load ellapp_filter %}
{% block content %}
<div class="container my-2">
    <!-- Question -->
    <!-- show message -->
    {% if messages %}
    <div class="alert alert-danger my-2" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-1">
        {{ question.subject }}
    </h2>
    <div class="card my-2">
        <div class="card-body">
            <div class="card-text">
                {{ question.content|mark }}
            </div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-1 text-end mx-2">
                    <div class="mb-1">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-1 text-end">
                    <div class="mb-1">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
            <div class="my-2">
                <a href="javascript:void(0)" data-uri="{% url 'ellapp:question_vote' question.id %}"
                   class="recommend btn btn-sm btn-outline-secondary">Recommend
                    <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
                </a>
                {% if request.user == question.author %}
                <a href="{% url 'ellapp:question_modify' question.id %}"
                   class="btn btn-sm btn-outline-secondary">Modify</a>
                <a href="javascript:void()" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'ellapp:question_delete' question.id %}">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- Answer -->
    <h5 class="border-bottom my-2 py-1">
        {{question.answer_set.count}} answer(s) found.
    </h5>
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-2">
        <div class="card-body">
            <div class="card-text">
                {{ answer.content|mark }}
            </div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-1 text-end mx-2">
                    <div class="mb-1">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-1 text-end">
                    <div class="mb-1">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-2">
                <a href="javascript:void(0)" data-uri="{% url 'ellapp:answer_vote' answer.id %}"
                   class="recommend btn btn-sm btn-outline-secondary"> Recommend
                    <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>
                {% if request.user == answer.author %}
                <a href="{% url 'ellapp:answer_modify' answer.id %}"
                   class="btn btn-sm btn-outline-secondary">Modify</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'ellapp:answer_delete' answer.id %}">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- Upload Answer -->
    <form action="{% url 'ellapp:answer_create' question.id %}" method="post" class="my-2">
        {% csrf_token %}
        <!-- Start of error display block -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- End of error display block -->
        <div class="mb-2">
            <label for="content" class="form-label">Your Answer</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                      name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="Upload Answer" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if (confirm("Are you sure to delete?")) {
                location.href = this.dataset.uri;
            };
        });
    });
    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("Are you sure to recommend?")) {
                location.href = this.dataset.uri;
            };
        });
    });
</script>
{% endblock %}

templates/ellapp/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-2 border-bottom pb-1">
        Add a question
    </h5>
    <form method="post">
        {% csrf_token %}
        <!-- Start of error display block -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- End of error display block -->
        <div class="mb-2">
            <label for="subject" class="form-label">Subject</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-2">
            <label for="content" class="form-label">Detail</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">
            Save
        </button>
    </form>
</div>
{% endblock %}

templates/ellapp/question_list.html
{% extends 'base.html' %}
{% load ellapp_filter %}
{% block content %}
<div class="container my-2">
    <div class="row my-2">
        <div class="col-6">
            <a href="{% url 'ellapp:question_create' %}" class="btn btn-primary">Add a Question</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control"
                       value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button"
                            id="btn_search">Search</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>No.</th>
            <th style="width:50%">Title</th>
            <th>Author</th>
            <th>Timestamp</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                <!-- no = total - start idx - curr idx + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'ellapp:detail' question.id %}">
                    {{ question.subject }}
                </a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">
                    {{ question.answer_set.count }}
                </span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">No question found.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- Start of pagination handler -->
    <ul class="pagination justify-content-center">
        <!-- previous page -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
               href="javascript:void(0)"> < </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"> < </a>
        </li>
        {% endif %}
        <!-- Page list -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
               href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}"
                href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- Next page -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}"
                href="javascript:void(0)"> > </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"> > </a>
        </li>
        {% endif %}
    </ul>
    <!-- End of pagination handler -->
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;
        document.getElementById('searchForm').submit();
    });
</script>
{% endblock %}